export const contactsData = [
  {
    id: 1,
    name: 'Béatrice',
    email: 'mcreavin0@squarespace.com',
    gender: 'Male',
  },
  {
    id: 2,
    name: 'Maïlys',
    email: 'carnet1@cloudflare.com',
    gender: 'Polygender',
  },
  {
    id: 3,
    name: 'Maëlys',
    email: 'lgoatcher2@sphinn.com',
    gender: 'Male',
  },
  {
    id: 4,
    name: 'Kuí',
    email: 'lglenny3@baidu.com',
    gender: 'Genderqueer',
  },
  {
    id: 5,
    name: 'Rébecca',
    email: 'zabbs4@adobe.com',
    gender: 'Male',
  },
  {
    id: 6,
    name: 'Joséphine',
    email: 'lcorneliussen5@foxnews.com',
    gender: 'Female',
  },
  {
    id: 7,
    name: 'Méline',
    email: 'cgedney6@reddit.com',
    gender: 'Male',
  },
  {
    id: 8,
    name: 'Kù',
    email: 'sgawkes7@trellian.com',
    gender: 'Male',
  },
  {
    id: 9,
    name: 'Ophélie',
    email: 'asheridan8@pinterest.com',
    gender: 'Polygender',
  },
  {
    id: 10,
    name: 'Irène',
    email: 'sdumbare9@stumbleupon.com',
    gender: 'Female',
  },
  {
    id: 11,
    name: 'Annotés',
    email: 'tcarswella@statcounter.com',
    gender: 'Male',
  },
  {
    id: 12,
    name: 'Marylène',
    email: 'brimourb@dailymotion.com',
    gender: 'Male',
  },
  {
    id: 13,
    name: 'Loïc',
    email: 'skasperc@phpbb.com',
    gender: 'Male',
  },
  {
    id: 14,
    name: 'Mylène',
    email: 'dcreffieldd@mlb.com',
    gender: 'Female',
  },
  {
    id: 15,
    name: 'Miléna',
    email: 'jferraronee@creativecommons.org',
    gender: 'Male',
  },
  {
    id: 16,
    name: 'Anaëlle',
    email: 'nfrancescof@pagesperso-orange.fr',
    gender: 'Female',
  },
  {
    id: 17,
    name: 'Håkan',
    email: 'kwillischg@symantec.com',
    gender: 'Female',
  },
  {
    id: 18,
    name: 'Frédérique',
    email: 'mstormonth@g.co',
    gender: 'Male',
  },
  {
    id: 19,
    name: 'Pélagie',
    email: 'dgosdeni@gizmodo.com',
    gender: 'Male',
  },
  {
    id: 20,
    name: 'Estève',
    email: 'aeliasenj@theglobeandmail.com',
    gender: 'Male',
  },
];
